[build-system]
requires = ["setuptools~=62.3", "wheel~=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.mypy]
check_untyped_defs = false

disallow_incomplete_defs = false
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false
disallow_untyped_defs = false

# Warn when a # type: ignore comment does not specify any error codes
enable_error_code = "ignore-without-code"

follow_imports = "silent"

ignore_missing_imports = true

no_implicit_reexport = false
no_implicit_optional = false

python_version = "3.9"

show_error_codes = true
strict_concatenate = false
strict_equality = false

warn_incomplete_stub = false
warn_unused_configs = false
warn_unused_ignores = false
warn_redundant_casts = false
warn_return_any = false
warn_unreachable = false

# EFM-htm is an invalid Python package name
exclude = "arelle/(plugin/validate/EFM-htm)"

# --- per-module options ---
[[tool.mypy.overrides]]
module = 'arelle.*'
ignore_errors = true

# --- strict typing ---
# when a directory is converted, file entries are replaced by directory entry
# when the library is converted, the above entry will be replaced (strict is demanded)
[[tool.mypy.overrides]]
module = [
    'arelle.plugin.validate.ESEF.Util'
]
strict = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unreachable = true
ignore_errors = false
