name: Run Xbrl Conformance Suites
on: pull_request_target

jobs:
  run-conformance-suite:
    permissions: read-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-path:
          - tests/integration_tests/validation/ESEF/test_esef_ixbrl_conformance_suite.py
          - tests/integration_tests/validation/ESEF/test_esef_xhtml_conformance_suite.py
          - tests/integration_tests/validation/test_utr_conformance_suite.py
    environment: integration-tests
    steps:
      - name: Download XBRL validation config
        run: |
          mkdir -p "$XDG_CONFIG_HOME/arelle/cache"
          curl -L "${{ secrets.XBRL_VALIDATION_CONFIG_URL }}" -o config.zip
          unzip -d "$XDG_CONFIG_HOME/arelle/cache" config.zip 'http/*' 'https/*'
          rm config.zip
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run integration tests with pytest
        env:
          CONFORMANCE_SUITES_TEST_MODE: OFFLINE
        run: pytest --disable-warnings ${{ matrix.test-path }}
