name: Release

on:
  release:
    types: [released]

jobs:
  python-package:
    uses: ./.github/workflows/python-package.yml
    secrets: inherit
  build-linux:
    uses: ./.github/workflows/build-and-release-linux.yml
    secrets: inherit
  build-macos:
    uses: ./.github/workflows/build-and-release-mac.yml
    secrets: inherit
  build-windows:
    uses: ./.github/workflows/build-and-release-windows.yml
    secrets: inherit
